# Generated by Django 6.0.4 on 2026-05-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Salary', 'Salary'), ('Others', 'Others')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card')], max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
